### ISSUE TITLE
Frontend build issue with `1.2.0`

### ISSUE THREAD

**Issue by ashah-te** [coditory/gradle-webjar-plugin#1]
Hello, I using for `gradle-webjar-plugin` to build a multi-module project.
When I use the version `1.2.0`, it seems to be erroring out when trying to only build the Frontend project.

**Error Log**
```
gradle build --dry-run
executing gradlew instead of gradle

FAILURE: Build failed with an exception.

* What went wrong:
org.gradle.api.plugins.JavaPluginExtension.getSourceSets()Lorg/gradle/api/tasks/SourceSetContainer;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
```

**Issue**
Cannot build frontend project on `1.2.0`

**How to reproduce**
Use the plugin version `1.2.0`
cd to frontend project
build using `./gradlew build` 

**Workaround**
Using version `1.1.0` allows to build the Frontend project successfully

**Comment by pmendelski** [comment]
@ashah-te thanks for reporting the issue.
I could reproduce the problem for gradle version < 7.1.
Could you update gradle to newer version and let me know if the problem still exists?

**Comment by ashah-te** [comment]
Ah I see, that did work out for me when upgrading to Gradle 7.4, thanks for looking into it.
